name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3
        with:
          path: jury-lookup/frontend

      - name: Install Dependencies for frontend
        run: |
          cd jury-lookup/frontend
          npm install

      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          repository: csumb-cst499-capstone/jury-lookup-frontend
          path: jury-lookup/backend

      - name: Install Dependencies for backend
        run: |
          cd jury-lookup/backend
          npm install

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Start Backend
        run: |
          cd jury-lookup/backend
          npm start &

      - name: Wait for Backend to Start
        run: sleep 10s

      - name: Start Frontend
        run: |
          cd jury-lookup/frontend
          npm start &

      - name: Wait for Frontend to Start
        run: sleep 10s

      - name: Run Cypress Tests
        run: |
          cd jury-lookup/frontend
          npx run cypress
