name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3

      - name: Install Dependencies for frontend
        run: npm install
        working-directory: jury-lookup-frontend

      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          repository: csumb-cst499-capstone/jury-lookup-backend

      - name: Install Dependencies for backend
        run: npm install
        working-directory: jury-lookup-backend

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Start Backend
        run: npm start &
        working-directory: jury-lookup-backend

      - name: Wait for Backend to Start
        run: sleep 10s

      - name: Start Frontend
        run: npm start &
        working-directory: jury-lookup-frontend

      - name: Wait for Frontend to Start
        run: sleep 10s

      - name: Run Cypress Tests
        run: npx run cypress
        working-directory: jury-lookup-frontend
