name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  LOGTAIL_SOURCE_TOKEN: ${{ secrets.TEST_LOGTAIL_SOURCE_TOKEN }}
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
  AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
  AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
  AUTH0_SCOPE: ${{ vars.AUTH0_SCOPE }}
  AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
  API_URL: ${{ vars.API_URL }}
  BASE_URL: ${{ vars.BASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
     
      - name: Checkout frontend
        uses: actions/checkout@v3
        with:
          path: jury-lookup-frontend

      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          repository: csumb-cst499-capstone/jury-lookup-backend
          token: ${{ secrets.token }}
          ref: main
          path: jury-lookup-backend
      - run: ls -la
        working-directory: jury-lookup-backend
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          working-directory: jury-lookup-frontend
          
      - name: Install Dependencies for frontend
        run: npm ci
        working-directory: jury-lookup-frontend
          
      - name: Install Dependencies for backend
        run: npm ci
        working-directory: jury-lookup-backend



      - name: Start Backend
        run: npm start &
        working-directory: jury-lookup-backend

      - name: Wait for Backend to Start
        run: sleep 10s

      - name: Start Frontend
        run: npm start &
        working-directory: jury-lookup-frontend

      - name: Wait for Frontend to Start
        run: sleep 10s

      - name: Run Cypress Tests
        run: npx run cypress
        working-directory: jury-lookup-frontend
